services:
  db:
    container_name: db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - '5432:5432'

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: